[project]
name = "grocery-billing-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=4.3.0",
    "email-validator>=2.2.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.48.1",
]
